### ISSUE TITLE
Require for Homebrew & Docker

### ISSUE THREAD

**Issue by DelightRun** [zjulug/mirrors-issue-tracker#11]
我觉得Homebrew和Docker现在的需求应该很大吧，目前主要是用清华的。
是否考虑增加Homebrew和Docker的支持？

**Comment by adoal** [comment]
下学期买来新的存储设备了再搞

**Comment by vxst** [comment]
Docker指的是Docker Engine吧...清华也没有mirror Dockerhub呀

**Comment by vxst** [comment]
Dockerhub一下子就是几十T的买的新设备也存不下...
