### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by DelightRun** [zjulug/mirrors-issue-tracker#12]
在校内网使用的时候，偶尔会遇到`mirrors.zju.edu.cn`被解析为IPv6地址的情况，从而出现`404 Not Found`的错误。

**Comment by adoal** [comment]
你在什么网段使用会出现这种情况？按理说校内不支持IPv6的网段里是不会解析出IPv6地址的……就算解析出来也应该是连不上而不是404啊。我可以抽空去你遇到的环境测试一下，前提是bug能在确定的条件下复现。

**Comment by vxst** [comment]
closed due to no follow up
