### ISSUE TITLE
The fedora repo is out of date

### ISSUE THREAD

**Issue by wfwf1997** [zjulug/mirrors-issue-tracker#13]
According to the metadata of `/fedora/updates/25/x86_64/repodata/`, the last synchronizing is at Feb 14, 2017, more than 2 months ago.

**Comment by vxst** [comment]
Working on it, as Fedora is one of the hugest repo, a little time is needed.

**Comment by vxst** [comment]
fixed

**Comment by wfwf1997** [comment]
It is out of date again(
