### ISSUE TITLE
Link to openSUSE repository return 500 Internal Server Error

### ISSUE THREAD

**Issue by TAXUEZJU** [zjulug/mirrors-issue-tracker#2]
Resources under this directory "mirrors.zju.edu.cn/opensuse/factory/repo/" can not approach. For example, when I request "mirrors.zju.edu.cn/opensuse/factory/repo/non-oss/", broswer will return 500 or 404. However, I try to access the same directory on "mirrors.ustc.edu.cn" or "mirrors.tuna.tsinghua.edu.cn" , it is OK.

**Comment by alick9188** [comment]
@vxst would like to know how you fixed the issue. Thanks!

**Comment by vxst** [comment]
As it's the symlink infinite cycling problem, you can choose either to unfollow symlink in the problematic folder, or remove the cycling symlink.

**Comment by alick9188** [comment]
@vxst thanks!

**Comment by alick9188** [comment]
@vxst I removed manually the broken symlinks in our (tuna's) opensuse mirror. But they seem to reappear after new sync. So I think it is also an issue of our upstream mirror. Can you let me know which upstream you are syncing from?
