### ISSUE TITLE
Can't MSYS2 use ArchLinux's configuration?

### ISSUE THREAD

**Issue by ZJUGuoShuai** [zjulug/mirrors-issue-tracker#20]
MSYS2 uses Pacman as its package control system which is the same in Arch Linux. And I replace the source server from the default to ZJU mirror server. And it showed me this:
错误：GPGME error: 无效的加密引擎
错误：GPGME error: 无效的加密引擎
错误：GPGME error: 无效的加密引擎
错误：数据库 'mingw32' 无效 (无效或已损坏的数据库 (PGP 签名))
错误：数据库 'mingw64' 无效 (无效或已损坏的数据库 (PGP 签名))
错误：数据库 'msys' 无效 (无效或已损坏的数据库 (PGP 签名))

**Comment by yujincheng08** [comment]
No. Plz use [the msys2 mirrors](http://mirrors.zju.edu.cn/msys2/)
