### ISSUE TITLE
Ubuntu missing *-updates *-backports and *-security

### ISSUE THREAD

**Issue by yujincheng08** [zjulug/mirrors-issue-tracker#25]
For instance, for artful, there is only
`artful/` in `dist/` and are no
```
artful-backports/
artful-proposed/
artful-security/
artful-updates/
```

**Comment by vxst** [comment]
Really?

http://mirrors.zju.edu.cn/ubuntu/dists/

It seems to be all right.

**Comment by yujincheng08** [comment]
？？？It becomes okay now😂
