### ISSUE TITLE
debian source outdated

### ISSUE THREAD

**Issue by comzyh** [zjulug/mirrors-issue-tracker#26]
> sudo apt update
> Hit:1 http://storage.googleapis.com/bazel-apt stable InRelease
> Ign:2 https://mirrors.zju.edu.cn/debian stretch InRelease
> Hit:3 https://mirrors.zju.edu.cn/debian stretch-updates InRelease
> Get:4 https://mirrors.zju.edu.cn/debian-security stretch/updates InRelease [94.3 kB]
> Hit:4 https://mirrors.zju.edu.cn/debian-security stretch/updates InRelease
> Hit:5 https://mirrors.zju.edu.cn/debian stretch Release   
> Get:6 https://mirrors-ustc.in.zjulearning.org/docker-ce/linux/debian stretch InRelease [39.1 kB]
> Hit:6 https://mirrors-ustc.in.zjulearning.org/docker-ce/linux/debian stretch InRelease
> Hit:8 https://nvidia.github.io/libnvidia-container/debian9/amd64  InRelease
> Hit:9 https://nvidia.github.io/nvidia-container-runtime/debian9/amd64  InRelease
> Hit:10 https://nvidia.github.io/nvidia-docker/debian9/amd64  InRelease                                                                                                                                            
> Reading package lists... Done                                                                                                                                                                                     
> E: Release file for https://mirrors.zju.edu.cn/debian/dists/stretch-updates/InRelease is expired (invalid since 1d 7h 45min 10s). Updates for this repository will not be applied.

当前时间

> sources.list.d date
> 2018年 07月 23日 星期一 12:15:21 CST

**Comment by comzyh** [comment]
另外求问 ZJU LUG 目前有无群组

**Comment by vxst** [comment]
fixed

**Comment by vxst** [comment]
telegram

**Comment by comzyh** [comment]
是公开群组吗

VXST <notifications@github.com> 于 2018年7月24日周二 09:46写道：

**Comment by vxst** [comment]
你加一下我？@thevxst
