### ISSUE TITLE
请求贵站加入 mirrorz.org

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [zjulug/mirrors-issue-tracker#30]
最近开发一个项目 https://github.com/ZenithalHourlyRate/mirrorz ，目的是将各个镜像站的信息汇总起来，形成类似黄页的东西，不知道贵站是否有兴趣加入该项目

Demo: [www.mirrorz.org](https://www.mirrorz.org)

**Comment by vxst** [comment]
好哦，以及我有mirrors.network，mirrors.services，mirrors.center之类的域名，需要的话可以给你NS，有兴趣的话可以给我发邮件哦

**Comment by ZenithalHourlyRate** [comment]
目前 https://mirrorz.org 有了全新的前端，特此供贵站参考。

贵站参与该项目需要贵站生成一份 mirrorz.json，具体格式与要求可以参考项目 README

**Comment by ZenithalHourlyRate** [comment]
目前各站可通过允许其他站使用其数据并编写前端的parser（参考[该目录](https://github.com/tuna/mirrorz/tree/master/src/parser)），使得该数据变为 `mirrorz.json` 的格式，从而能实时反映相关的同步状态。这与之前各站需要提供 `mirrorz.json` 的方式不同。

贵站使用静态前端，由于数据较为不规则，较难书写相关的 parser，希望能得到相关人员的协助，或者贵站提供相应的数据。
