### ISSUE TITLE
是否能增加 ArchLinuxCN repo？

### ISSUE THREAD

**Issue by zsrkmyn** [zjulug/mirrors-issue-tracker#9]
虽然用 163 的还不错啦，但是校内毕竟可以到 10+MBps 的速度呢。
https://github.com/archlinuxcn/repo
https://github.com/archlinuxcn/mirrorlist-repo
http://repo.archlinuxcn.org/

**Comment by vxst** [comment]
你试一下？现在已经加了

如果正常的话我就把它加到主页上了..

**Comment by zsrkmyn** [comment]
看起来没问题，thanks a lot :D

**Comment by yejingchen** [comment]
加了 CN 源的话跟 ArchLinuxCN 社区联系一下加到 `archlinuxcn-mirrorlist` 里呗？这样其他 CN 源用户也可以直接在 mirrorlist 文件里开启浙大源了。
[https://github.com/archlinuxcn/mirrorlist-repo](url)

P.S. 浙大源支持 HTTPS，但是在 Arch 官方 mirrorlist 里却没有 HTTPS 呢，不知道找哪里反映

**Comment by vxst** [comment]
Arch是通过包签名保证安全性的，其实并不是那么需要https

我们一般在正常运行1-2个月，有了几个比较稳定的上游源后才会去提交官方列表

**Comment by zsrkmyn** [comment]
其实似乎也可以直接发邮件到 repo@archlinuxcn.org 要 rsync 地址和账户密码来同步。不知道现在的上游是哪里。

**Comment by vxst** [comment]
因为带宽分配问题我们比较倾向于CERNET和IPV6，所以不能每个repo都同步官方源；现在是清华

VXST
